services:
  postgres:
    image: postgres:16-alpine
    container_name: rik_proovitoo_postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=rik_proovitöö
      - POSTGRES_USER=rik_proovitöö
      - POSTGRES_PASSWORD=rik_proovitöö
      - POSTGRES_INITDB_ARGS=--data-checksums
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
  rik_proovitoo:
    build: .
    image: laurielias/rik_proovitoo:latest
    container_name: rik_proovitoo
    # ports:
    #   - 8000:8000 # Django
    # volumes:
    #   - .:/home/docker/rik_proovitöö
    # entrypoint: 'docker-entrypoint-dev.sh'
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - postgres