services:
  postgres:
    image: postgres:16-alpine
    container_name: rik_proovitoo_postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=rik_proovitöö
      - POSTGRES_USER=rik_proovitöö
      - POSTGRES_PASSWORD=rik_proovitöö
      - POSTGRES_INITDB_ARGS=--data-checksums
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
