# Generated by Django 5.0.7 on 2024-07-21 06:55

import django.contrib.postgres.indexes
import django.core.validators
import django.db.models.deletion
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations, models

import rik_proovitöö.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        TrigramExtension(),
        migrations.CreateModel(
            name='LegalEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3)])),
                ('code', models.IntegerField(validators=[django.core.validators.MinValueValidator(1000000),
                                                         django.core.validators.MaxValueValidator(99999999999)])),
                ('creation_date', models.DateField(blank=True, validators=[rik_proovitöö.models.no_future_date])),
                ('capital', models.IntegerField(null=True)),
                ('is_person', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Legal entity',
                'verbose_name_plural': 'Legal entities',
                'indexes': [models.Index(fields=['code'], name='rik_proovit_code_9aef16_idx'),
                            django.contrib.postgres.indexes.GinIndex(fields=['name'], name='gin_trgm_idx',
                                                                     opclasses=['gin_trgm_ops'])],
            },
            bases=(models.Model, rik_proovitöö.models.CreatedUpdatedMixin),
        ),
        migrations.CreateModel(
            name='Equity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('is_founding', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stakes',
                                              to='rik_proovitöö.legalentity')),
                ('stakeholder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings',
                                                  to='rik_proovitöö.legalentity')),
            ],
            options={
                'verbose_name': 'Equity',
                'verbose_name_plural': 'Holdings',
                'unique_together': {('stakeholder', 'company')},
            },
            bases=(models.Model, rik_proovitöö.models.CreatedUpdatedMixin),
        ),
    ]
