# Generated by Django 5.0.7 on 2024-07-21 06:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('rik_proovitöö', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legalentity',
            name='code',
            field=models.BigIntegerField(validators=[django.core.validators.MinValueValidator(1000000),
                                                     django.core.validators.MaxValueValidator(99999999999)]),
        ),
    ]
