# Generated by Django 5.0.7 on 2024-07-21 08:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('rik_proovitöö', '0003_alter_legalentity_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legalentity',
            name='capital',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
