# Generated by Django 5.0.7 on 2024-07-25 17:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('rik_proovitöö', '0004_alter_legalentity_capital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legalentity',
            name='code',
            field=models.BigIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1000000),
                                                                  django.core.validators.MaxValueValidator(
                                                                      99999999999)]),
        ),
    ]
