# Generated by Django 5.0.7 on 2024-07-29 18:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

import rik_proovitöö.models


class Migration(migrations.Migration):
    dependencies = [
        ('rik_proovitöö', '0005_alter_legalentity_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equity',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stakes',
                                    to='rik_proovitöö.legalentity', verbose_name='company'),
        ),
        migrations.AlterField(
            model_name='equity',
            name='is_founding',
            field=models.BooleanField(default=True, verbose_name='is founding'),
        ),
        migrations.AlterField(
            model_name='equity',
            name='stakeholder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings',
                                    to='rik_proovitöö.legalentity', verbose_name='stakeholder'),
        ),
        migrations.AlterField(
            model_name='equity',
            name='value',
            field=models.IntegerField(verbose_name='value'),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='capital',
            field=models.IntegerField(blank=True, null=True, verbose_name='capital'),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='code',
            field=models.BigIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1000000),
                                                                  django.core.validators.MaxValueValidator(
                                                                      99999999999)], verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='creation_date',
            field=models.DateField(blank=True, null=True, validators=[rik_proovitöö.models.no_future_date],
                                   verbose_name='creation date'),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='is_person',
            field=models.BooleanField(default=False, verbose_name='is person'),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3)],
                                   verbose_name='name'),
        ),
    ]
