name: Django application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: rik_proovitöö
          POSTGRES_USER: rik_proovitöö
          POSTGRES_PASSWORD: rik_proovitöö
        options: >-
          --health-cmd "pg_isready -U ${{ secrets.POSTGRES_USER }}" 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 5

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.12.4
        uses: actions/setup-python@v2
        with:
          python-version: 3.12.4
      - name: Install dependencies
        run: |
          python -m pip install -r requirements.txt -r requirements.test.txt
      - name: Set up database
        run: |
          sudo apt-get install -y postgresql-client
          psql -h localhost -U rik_proovitöö -d rik_proovitöö -c "CREATE EXTENSION IF NOT EXISTS pg_trgm;"
        env:
          PGPASSWORD: rik_proovitöö
      - name: Test with pytest
        run: |
          pytest
        env:
          DATABASE_URL: postgres://rik_proovitöö:rik_proovitöö@localhost:5432/rik_proovitöö
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true